on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@1.5.0
    with:
      module-name: PsMermaidTools
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
